name: Compilation ft_irc

on:
  push:
    branches:
      - main

jobs:
  verif:
      runs-on: ubuntu-22.04 macos-13 #change to mac
      steps:
          - uses : actions/checkout@v2
          - name : Compile ft_irc
            run : |
              make 